import fs from 'fs';
import path from 'path';
import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

dotenv.config();
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/sustainability_dashboard';

// Minimal Indicator model (matches backend model shape)
const indicatorSchema = new mongoose.Schema({
  timestamp: Date,
  renewableEnergyPercent: Number,
  waterUsage: Number,
  wasteDiverted: Number,
  ghgEmissions: Number,
  notes: String
}, { collection: 'indicators' });

const Indicator = mongoose.model('Indicator', indicatorSchema);

async function generate() {
  await mongoose.connect(MONGO_URI);
  const latest = await Indicator.findOne().sort({ timestamp: -1 }).lean();
  const data = latest || {
    renewableEnergyPercent: '—',
    waterUsage: '—',
    wasteDiverted: '—',
    ghgEmissions: '—',
    notes: ''
  };

  const html = `<!doctype html>
  <html>
  <head>
    <meta charset="utf-8" />
    <title>SID One-page Summary</title>
    <style>
      body { font-family: Arial, Helvetica, sans-serif; margin: 40px; color: #222 }
      header { text-align:center }
      .kpis { display:flex; gap:20px; justify-content:center; margin-top:20px }
      .kpi { background:#f7f7f7;padding:20px;border-radius:8px; min-width:140px; text-align:center }
      footer { margin-top:40px; font-size:0.9rem; color:#666 }
    </style>
  </head>
  <body>
    <header>
      <h1>SID — Sustainability Indicators Dashboard</h1>
      <p>One-page summary — live sample metrics</p>
    </header>

    <section class="kpis">
      <div class="kpi"><h2>${data.renewableEnergyPercent}%</h2><div>Renewable Energy</div></div>
      <div class="kpi"><h2>${data.waterUsage}</h2><div>Water (m³)</div></div>
      <div class="kpi"><h2>${data.wasteDiverted}%</h2><div>Waste Diverted</div></div>
      <div class="kpi"><h2>${data.ghgEmissions}</h2><div>GHG (tCO2e)</div></div>
    </section>

    <section style="margin-top:30px;">
      <h3>Notes</h3>
      <p>${data.notes || 'No notes available.'}</p>
    </section>

    <footer>
      <p>Generated by SID — ${new Date().toLocaleString()}</p>
    </footer>
  </body>
  </html>`;

  const outHtml = path.join(__dirname, 'onepage_summary.html');
  fs.writeFileSync(outHtml, html, 'utf8');
  console.log('Wrote HTML summary to', outHtml);

  // Attempt to generate PDF via puppeteer if available
  try {
    const puppeteer = await import('puppeteer');
    const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const outPdf = path.join(__dirname, 'onepage_summary.pdf');
    await page.pdf({ path: outPdf, format: 'A4', printBackground: true });
    await browser.close();
    console.log('Wrote PDF summary to', outPdf);
  } catch (err) {
    console.log('puppeteer not available or PDF generation failed — only HTML was written.');
    console.log('To generate PDF install puppeteer: npm install puppeteer --save');
  }

  await mongoose.disconnect();
}

if (require.main === module) {
  generate().catch(err => { console.error(err); process.exit(1); });
}

export default generate;
